version: '3.8'

services:
  echidna:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_BOT_CLIENT_ID=${DISCORD_BOT_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_OP_USER_ID=${DISCORD_OP_USER_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_URL=${OPENROUTER_URL}
      - LAVA_LINK_PASSWORD=${LAVA_LINK_PASSWORD}
      - LAVA_LINK_HOST=${LAVA_LINK_HOST}
      - RUNPOD_TOKEN=${RUNPOD_TOKEN}
      - WAIFU_GENERATOR_ENDPOINT=${WAIFU_GENERATOR_ENDPOINT}
      - DANBOORU_ENDPOINT=${DANBOORU_ENDPOINT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_ACCESS=${JWT_SECRET_ACCESS}
      - JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
    ports:
      - 3069:3069
