version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - SERVER_COUNTRIES=United States
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - FREE_ONLY=on
      - FIREWALL_OUTBOUND_SUBNETS=${DATABASE_IP_RANGE}
  echidna:
    build: .
    depends_on:
      - gluetun
    network_mode: service:gluetun
    restart: unless-stopped
